.\"                                      Hey, EMACS: -*- nroff -*-
.TH BLIMP-DCRAW 1 "April  6, 2007"
.SH NAME
blimp-dcraw \- dcraw executable for Blimp
.SH SYNOPSIS
.B blimp-dcraw
.RI [ options ] " files" ...
.BR
.SH DESCRIPTION
.B blimp-dcraw
is a is a version of David Coffin's
.B dcraw
compiled for use by the Blimp photo editor.
dcraw is a decoder for raw digital photos.
.PP
See the
.BR dcraw
man page for more details.
.SH SEE ALSO
.BR dcraw (1),
.BR blimp (1)
.SH AUTHOR
David Coffin
