.\"                                      Hey, EMACS: -*- nroff -*-
.TH BLIMP 1 "August  8, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
blimp \- a layered photo editor
.SH SYNOPSIS
.B blimp
.\"RI [ options ] " files" ...
.\"br
.SH DESCRIPTION
.B Blimp
is a layer-based photo editor.  It supports
many raw formats (through dcraw), 8-bit or 16-bit
color depth per channel and editing operations
including curves, grayscale mixer, resize and
unsharp mask, all of which are adjustment layers.
.SH SEE ALSO
.BR dcraw (1)
.PP
More documentation for Blimp can be found at the project wiki:
.BR
https://projects.boblycat.org/blimp
.SH AUTHOR
Knut Arild Erstad <knutae@gmail.com>
